name: Generate Commits HTML

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Code ophalen
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 0 = volledige geschiedenis ophalen; 50 = laatste 50 commits ophalen;
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Genereer commits HTML
        run: |
          set -e
          out=GeneratedCommits.html

          cat > "$out" <<'HTML'
          <html><head><title>Generated Commits</title><link rel="stylesheet" href="css.css"></head><body><h1>Commits</h1>
          HTML
          echo "<h2>Latest Pull Request Commits</h2>" >> "$out"

          git log --merges --pretty=format:"%H|%ad|%an|%s" --date=format:'%Y-%m-%d %H:%M' | while IFS='|' read -r sha date author subject; do
            branch=$(echo "$subject" | sed -n "s/.* from \(.*\)/\1/p")
            if [ -z "$branch" ]; then
              # als de branch niet uit de subject gehaald kan worden, gebruik de hele subject als fallback
              branch="$subject"
            fi

            echo "<h2>$branch</h2>" >> "$out"
            echo "<ul>" >> "$out"

            parents=$(git rev-list --parents -n 1 "$sha")
            set -- $parents
            # $1 = merge sha, $2 = parent1 (target/main), $3 = parent2 (source/branch)
            parent1=$2
            parent2=$3

            if [ -n "$parent1" ] && [ -n "$parent2" ]; then
              git log "$parent1".."$parent2" --pretty=format:"<li>%ad - %an: %s</li>" --date=format:'%Y-%m-%d %H:%M' >> "$out" || true
            else
              echo "<li>$date - $author: $subject</li>" >> "$out"
            fi

            echo "</ul>" >> "$out"
          done

          # Non pull request merges
          echo "<h2>Other Commits</h2><ul>" >> "$out"

          # haal alle commits die op braches zijn gemerged
          merged_commits=$(git log --merges --pretty=format:"%H" | while read -r merge_sha; do
            parents=$(git rev-list --parents -n 1 "$merge_sha")
            set -- $parents
            parent1=$2
            parent2=$3
            [ -n "$parent1" ] && [ -n "$parent2" ] && git rev-list "$parent1".."$parent2"
          done)

          # print alle commits die niet in de merged commits zitten
          git log --no-merges --pretty=format:"%H|%ad|%an|%s" --date=format:'%Y-%m-%d %H:%M' | while IFS='|' read -r sha date author subject; do
            if ! echo "$merged_commits" | grep -q "$sha"; then
              echo "<li>$date - $author: $subject</li>" >> "$out"
            fi
          done

          echo "</ul>" >> "$out"

          echo "</body></html>" >> "$out"


      - name: Commit en push HTML
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add GeneratedCommits.html
          git commit -m "Update GeneratedCommits.html" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
