name: Generate Commits HTML

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Code ophalen
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 0 = volledige geschiedenis ophalen; 50 = laatste 50 commits ophalen;
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Genereer commits HTML
        run: |
          echo "<html><head><title>Commits</title></head><body><h1>Commits per branch</h1>" > commits.html

          # Haal alle lokale branches op
          for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/); do
            echo "<h2>$branch</h2><ul>" >> commits.html
            # Toon commits van die branch (niet in andere branches)
            git log $branch --not --all --pretty=format:"<li>%ad - %an: %s</li>" --date=format:'%Y-%m-%d %H:%M' >> commits.html
            echo "</ul>" >> commits.html
          done

          echo "</body></html>" >> commits.html


      - name: Commit en push HTML
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add commits.html
          git commit -m "Update commits.html" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
