name: Generate Commits HTML

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Code ophalen
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 0 = volledige geschiedenis ophalen; 50 = laatste 50 commits ophalen;
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Genereer commits HTML
        run: |
          echo "<html><head><title>Commits</title></head><body><h1>Commits</h1>" > GeneratedCommits.html

          echo "<h2>Latest Pull Request Commits</h2><ul>" >> GeneratedCommits.html
          git log --merges --pretty=format:"<li>%ad - %an: %s</li>" --date=format:'%Y-%m-%d %H:%M' >> GeneratedCommits.html
          echo "</ul>" >> GeneratedCommits.html

          echo "<h2>Other Commits</h2><ul>" >> GeneratedCommits.html
          git log --no-merges --pretty=format:"<li>%ad - %an: %s</li>" --date=format:'%Y-%m-%d %H:%M' >> GeneratedCommits.html
          echo "</ul></body></html>" >> GeneratedCommits.html


      - name: Commit en push HTML
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add GeneratedCommits.html
          git commit -m "Update GeneratedCommits.html" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
