name: Generate Commits HTML

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Code ophalen
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 0 = volledige geschiedenis ophalen; 50 = laatste 50 commits ophalen;
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Genereer commits HTML
        run: |
          BRANCH_NAME=${GITHUB_REF_NAME}
          echo "<html><head><title>Commits</title></head><body><h1>Commits van $BRANCH_NAME</h1><ul>" > commits.html
          git log $BRANCH_NAME --pretty=format:"<li>%ad - %an: %s</li>" --date=format:'%Y-%m-%d %H:%M' >> commits.html
          echo "</ul></body></html>" >> commits.html

      - name: Commit en push HTML
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add commits.html
          git commit -m "Update commits.html" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
